# Generated by Django 3.2.8 on 2021-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
